// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 05 Nov 2019 17:44:23 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "raylib.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

