// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 05 Nov 2019 17:44:23 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package ray

/*
#include "raylib.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// PI as defined in ray/raylib.h:91
	PI = 3.14159265358979323846
	// DEG2RAD as defined in ray/raylib.h:94
	DEG2RAD = (PI / 180.0)
	// RAD2DEG as defined in ray/raylib.h:95
	RAD2DEG = (180.0 / PI)
	// MAXTOUCHPOINTS as defined in ray/raylib.h:97
	MAXTOUCHPOINTS = 10
	// FormatText as defined in ray/raylib.h:150
	FormatText = 0
	// SubText as defined in ray/raylib.h:151
	SubText = 0
	// ShowWindow as defined in ray/raylib.h:152
	ShowWindow = 0
	// LOCMAPDIFFUSE as defined in ray/raylib.h:702
	LOCMAPDIFFUSE = 0
	// LOCMAPSPECULAR as defined in ray/raylib.h:703
	LOCMAPSPECULAR = 0
	// MAPDIFFUSE as defined in ray/raylib.h:733
	MAPDIFFUSE = 0
	// MAPSPECULAR as defined in ray/raylib.h:734
	MAPSPECULAR = 0
)

// ConfigFlag as declared in ray/raylib.h:471
type ConfigFlag int32

// ConfigFlag enumeration from ray/raylib.h:471
const (
	FLAGRESERVED          ConfigFlag = 1
	FLAGFULLSCREENMODE    ConfigFlag = 2
	FLAGWINDOWRESIZABLE   ConfigFlag = 4
	FLAGWINDOWUNDECORATED ConfigFlag = 8
	FLAGWINDOWTRANSPARENT ConfigFlag = 16
	FLAGWINDOWHIDDEN      ConfigFlag = 128
	FLAGWINDOWALWAYSRUN   ConfigFlag = 256
	FLAGMSAA4XHINT        ConfigFlag = 32
	FLAGVSYNCHINT         ConfigFlag = 64
)

// KeyboardKey as declared in ray/raylib.h:597
type KeyboardKey int32

// KeyboardKey enumeration from ray/raylib.h:597
const (
	KEYAPOSTROPHE   KeyboardKey = 39
	KEYCOMMA        KeyboardKey = 44
	KEYMINUS        KeyboardKey = 45
	KEYPERIOD       KeyboardKey = 46
	KEYSLASH        KeyboardKey = 47
	KEYZERO         KeyboardKey = 48
	KEYONE          KeyboardKey = 49
	KEYTWO          KeyboardKey = 50
	KEYTHREE        KeyboardKey = 51
	KEYFOUR         KeyboardKey = 52
	KEYFIVE         KeyboardKey = 53
	KEYSIX          KeyboardKey = 54
	KEYSEVEN        KeyboardKey = 55
	KEYEIGHT        KeyboardKey = 56
	KEYNINE         KeyboardKey = 57
	KEYSEMICOLON    KeyboardKey = 59
	KEYEQUAL        KeyboardKey = 61
	KEYA            KeyboardKey = 65
	KEYB            KeyboardKey = 66
	KEYC            KeyboardKey = 67
	KEYD            KeyboardKey = 68
	KEYE            KeyboardKey = 69
	KEYF            KeyboardKey = 70
	KEYG            KeyboardKey = 71
	KEYH            KeyboardKey = 72
	KEYI            KeyboardKey = 73
	KEYJ            KeyboardKey = 74
	KEYK            KeyboardKey = 75
	KEYL            KeyboardKey = 76
	KEYM            KeyboardKey = 77
	KEYN            KeyboardKey = 78
	KEYO            KeyboardKey = 79
	KEYP            KeyboardKey = 80
	KEYQ            KeyboardKey = 81
	KEYR            KeyboardKey = 82
	KEYS            KeyboardKey = 83
	KEYT            KeyboardKey = 84
	KEYU            KeyboardKey = 85
	KEYV            KeyboardKey = 86
	KEYW            KeyboardKey = 87
	KEYX            KeyboardKey = 88
	KEYY            KeyboardKey = 89
	KEYZ            KeyboardKey = 90
	KEYSPACE        KeyboardKey = 32
	KEYESCAPE       KeyboardKey = 256
	KEYENTER        KeyboardKey = 257
	KEYTAB          KeyboardKey = 258
	KEYBACKSPACE    KeyboardKey = 259
	KEYINSERT       KeyboardKey = 260
	KEYDELETE       KeyboardKey = 261
	KEYRIGHT        KeyboardKey = 262
	KEYLEFT         KeyboardKey = 263
	KEYDOWN         KeyboardKey = 264
	KEYUP           KeyboardKey = 265
	KEYPAGEUP       KeyboardKey = 266
	KEYPAGEDOWN     KeyboardKey = 267
	KEYHOME         KeyboardKey = 268
	KEYEND          KeyboardKey = 269
	KEYCAPSLOCK     KeyboardKey = 280
	KEYSCROLLLOCK   KeyboardKey = 281
	KEYNUMLOCK      KeyboardKey = 282
	KEYPRINTSCREEN  KeyboardKey = 283
	KEYPAUSE        KeyboardKey = 284
	KEYF1           KeyboardKey = 290
	KEYF2           KeyboardKey = 291
	KEYF3           KeyboardKey = 292
	KEYF4           KeyboardKey = 293
	KEYF5           KeyboardKey = 294
	KEYF6           KeyboardKey = 295
	KEYF7           KeyboardKey = 296
	KEYF8           KeyboardKey = 297
	KEYF9           KeyboardKey = 298
	KEYF10          KeyboardKey = 299
	KEYF11          KeyboardKey = 300
	KEYF12          KeyboardKey = 301
	KEYLEFTSHIFT    KeyboardKey = 340
	KEYLEFTCONTROL  KeyboardKey = 341
	KEYLEFTALT      KeyboardKey = 342
	KEYLEFTSUPER    KeyboardKey = 343
	KEYRIGHTSHIFT   KeyboardKey = 344
	KEYRIGHTCONTROL KeyboardKey = 345
	KEYRIGHTALT     KeyboardKey = 346
	KEYRIGHTSUPER   KeyboardKey = 347
	KEYKBMENU       KeyboardKey = 348
	KEYLEFTBRACKET  KeyboardKey = 91
	KEYBACKSLASH    KeyboardKey = 92
	KEYRIGHTBRACKET KeyboardKey = 93
	KEYGRAVE        KeyboardKey = 96
	KEYKP0          KeyboardKey = 320
	KEYKP1          KeyboardKey = 321
	KEYKP2          KeyboardKey = 322
	KEYKP3          KeyboardKey = 323
	KEYKP4          KeyboardKey = 324
	KEYKP5          KeyboardKey = 325
	KEYKP6          KeyboardKey = 326
	KEYKP7          KeyboardKey = 327
	KEYKP8          KeyboardKey = 328
	KEYKP9          KeyboardKey = 329
	KEYKPDECIMAL    KeyboardKey = 330
	KEYKPDIVIDE     KeyboardKey = 331
	KEYKPMULTIPLY   KeyboardKey = 332
	KEYKPSUBTRACT   KeyboardKey = 333
	KEYKPADD        KeyboardKey = 334
	KEYKPENTER      KeyboardKey = 335
	KEYKPEQUAL      KeyboardKey = 336
)

// AndroidButton as declared in ray/raylib.h:605
type AndroidButton int32

// AndroidButton enumeration from ray/raylib.h:605
const (
	KEYBACK       AndroidButton = 4
	KEYMENU       AndroidButton = 82
	KEYVOLUMEUP   AndroidButton = 24
	KEYVOLUMEDOWN AndroidButton = 25
)

// MouseButton as declared in ray/raylib.h:612
type MouseButton int32

// MouseButton enumeration from ray/raylib.h:612
const (
	MOUSELEFTBUTTON   MouseButton = iota
	MOUSERIGHTBUTTON  MouseButton = 1
	MOUSEMIDDLEBUTTON MouseButton = 2
)

// GamepadNumber as declared in ray/raylib.h:620
type GamepadNumber int32

// GamepadNumber enumeration from ray/raylib.h:620
const (
	GAMEPADPLAYER1 GamepadNumber = iota
	GAMEPADPLAYER2 GamepadNumber = 1
	GAMEPADPLAYER3 GamepadNumber = 2
	GAMEPADPLAYER4 GamepadNumber = 3
)

// GamepadButton as declared in ray/raylib.h:654
type GamepadButton int32

// GamepadButton enumeration from ray/raylib.h:654
const (
	GAMEPADBUTTONUNKNOWN        GamepadButton = iota
	GAMEPADBUTTONLEFTFACEUP     GamepadButton = 1
	GAMEPADBUTTONLEFTFACERIGHT  GamepadButton = 2
	GAMEPADBUTTONLEFTFACEDOWN   GamepadButton = 3
	GAMEPADBUTTONLEFTFACELEFT   GamepadButton = 4
	GAMEPADBUTTONRIGHTFACEUP    GamepadButton = 5
	GAMEPADBUTTONRIGHTFACERIGHT GamepadButton = 6
	GAMEPADBUTTONRIGHTFACEDOWN  GamepadButton = 7
	GAMEPADBUTTONRIGHTFACELEFT  GamepadButton = 8
	GAMEPADBUTTONLEFTTRIGGER1   GamepadButton = 9
	GAMEPADBUTTONLEFTTRIGGER2   GamepadButton = 10
	GAMEPADBUTTONRIGHTTRIGGER1  GamepadButton = 11
	GAMEPADBUTTONRIGHTTRIGGER2  GamepadButton = 12
	GAMEPADBUTTONMIDDLELEFT     GamepadButton = 13
	GAMEPADBUTTONMIDDLE         GamepadButton = 14
	GAMEPADBUTTONMIDDLERIGHT    GamepadButton = 15
	GAMEPADBUTTONLEFTTHUMB      GamepadButton = 16
	GAMEPADBUTTONRIGHTTHUMB     GamepadButton = 17
)

// GamepadAxis as declared in ray/raylib.h:671
type GamepadAxis int32

// GamepadAxis enumeration from ray/raylib.h:671
const (
	GAMEPADAXISUNKNOWN      GamepadAxis = iota
	GAMEPADAXISLEFTX        GamepadAxis = 1
	GAMEPADAXISLEFTY        GamepadAxis = 2
	GAMEPADAXISRIGHTX       GamepadAxis = 3
	GAMEPADAXISRIGHTY       GamepadAxis = 4
	GAMEPADAXISLEFTTRIGGER  GamepadAxis = 5
	GAMEPADAXISRIGHTTRIGGER GamepadAxis = 6
)

// ShaderLocationIndex as declared in ray/raylib.h:700
type ShaderLocationIndex int32

// ShaderLocationIndex enumeration from ray/raylib.h:700
const (
	LOCVERTEXPOSITION   ShaderLocationIndex = iota
	LOCVERTEXTEXCOORD01 ShaderLocationIndex = 1
	LOCVERTEXTEXCOORD02 ShaderLocationIndex = 2
	LOCVERTEXNORMAL     ShaderLocationIndex = 3
	LOCVERTEXTANGENT    ShaderLocationIndex = 4
	LOCVERTEXCOLOR      ShaderLocationIndex = 5
	LOCMATRIXMVP        ShaderLocationIndex = 6
	LOCMATRIXMODEL      ShaderLocationIndex = 7
	LOCMATRIXVIEW       ShaderLocationIndex = 8
	LOCMATRIXPROJECTION ShaderLocationIndex = 9
	LOCVECTORVIEW       ShaderLocationIndex = 10
	LOCCOLORDIFFUSE     ShaderLocationIndex = 11
	LOCCOLORSPECULAR    ShaderLocationIndex = 12
	LOCCOLORAMBIENT     ShaderLocationIndex = 13
	LOCMAPALBEDO        ShaderLocationIndex = 14
	LOCMAPMETALNESS     ShaderLocationIndex = 15
	LOCMAPNORMAL        ShaderLocationIndex = 16
	LOCMAPROUGHNESS     ShaderLocationIndex = 17
	LOCMAPOCCLUSION     ShaderLocationIndex = 18
	LOCMAPEMISSION      ShaderLocationIndex = 19
	LOCMAPHEIGHT        ShaderLocationIndex = 20
	LOCMAPCUBEMAP       ShaderLocationIndex = 21
	LOCMAPIRRADIANCE    ShaderLocationIndex = 22
	LOCMAPPREFILTER     ShaderLocationIndex = 23
	LOCMAPBRDF          ShaderLocationIndex = 24
)

// ShaderUniformDataType as declared in ray/raylib.h:716
type ShaderUniformDataType int32

// ShaderUniformDataType enumeration from ray/raylib.h:716
const (
	UNIFORMFLOAT     ShaderUniformDataType = iota
	UNIFORMVEC2      ShaderUniformDataType = 1
	UNIFORMVEC3      ShaderUniformDataType = 2
	UNIFORMVEC4      ShaderUniformDataType = 3
	UNIFORMINT       ShaderUniformDataType = 4
	UNIFORMIVEC2     ShaderUniformDataType = 5
	UNIFORMIVEC3     ShaderUniformDataType = 6
	UNIFORMIVEC4     ShaderUniformDataType = 7
	UNIFORMSAMPLER2D ShaderUniformDataType = 8
)

// MaterialMapType as declared in ray/raylib.h:731
type MaterialMapType int32

// MaterialMapType enumeration from ray/raylib.h:731
const (
	MAPALBEDO     MaterialMapType = iota
	MAPMETALNESS  MaterialMapType = 1
	MAPNORMAL     MaterialMapType = 2
	MAPROUGHNESS  MaterialMapType = 3
	MAPOCCLUSION  MaterialMapType = 4
	MAPEMISSION   MaterialMapType = 5
	MAPHEIGHT     MaterialMapType = 6
	MAPCUBEMAP    MaterialMapType = 7
	MAPIRRADIANCE MaterialMapType = 8
	MAPPREFILTER  MaterialMapType = 9
	MAPBRDF       MaterialMapType = 10
)

// PixelFormat as declared in ray/raylib.h:760
type PixelFormat int32

// PixelFormat enumeration from ray/raylib.h:760
const (
	UNCOMPRESSEDGRAYSCALE    PixelFormat = 1
	UNCOMPRESSEDGRAYALPHA    PixelFormat = 2
	UNCOMPRESSEDR5G6B5       PixelFormat = 3
	UNCOMPRESSEDR8G8B8       PixelFormat = 4
	UNCOMPRESSEDR5G5B5A1     PixelFormat = 5
	UNCOMPRESSEDR4G4B4A4     PixelFormat = 6
	UNCOMPRESSEDR8G8B8A8     PixelFormat = 7
	UNCOMPRESSEDR32          PixelFormat = 8
	UNCOMPRESSEDR32G32B32    PixelFormat = 9
	UNCOMPRESSEDR32G32B32A32 PixelFormat = 10
	COMPRESSEDDXT1RGB        PixelFormat = 11
	COMPRESSEDDXT1RGBA       PixelFormat = 12
	COMPRESSEDDXT3RGBA       PixelFormat = 13
	COMPRESSEDDXT5RGBA       PixelFormat = 14
	COMPRESSEDETC1RGB        PixelFormat = 15
	COMPRESSEDETC2RGB        PixelFormat = 16
	COMPRESSEDETC2EACRGBA    PixelFormat = 17
	COMPRESSEDPVRTRGB        PixelFormat = 18
	COMPRESSEDPVRTRGBA       PixelFormat = 19
	COMPRESSEDASTC4x4RGBA    PixelFormat = 20
	COMPRESSEDASTC8x8RGBA    PixelFormat = 21
)

// TextureFilterMode as declared in ray/raylib.h:772
type TextureFilterMode int32

// TextureFilterMode enumeration from ray/raylib.h:772
const (
	FILTERPOINT          TextureFilterMode = iota
	FILTERBILINEAR       TextureFilterMode = 1
	FILTERTRILINEAR      TextureFilterMode = 2
	FILTERANISOTROPIC4X  TextureFilterMode = 3
	FILTERANISOTROPIC8X  TextureFilterMode = 4
	FILTERANISOTROPIC16X TextureFilterMode = 5
)

// CubemapLayoutType as declared in ray/raylib.h:782
type CubemapLayoutType int32

// CubemapLayoutType enumeration from ray/raylib.h:782
const (
	CUBEMAPAUTODETECT       CubemapLayoutType = iota
	CUBEMAPLINEVERTICAL     CubemapLayoutType = 1
	CUBEMAPLINEHORIZONTAL   CubemapLayoutType = 2
	CUBEMAPCROSSTHREEBYFOUR CubemapLayoutType = 3
	CUBEMAPCROSSFOURBYTHREE CubemapLayoutType = 4
	CUBEMAPPANORAMA         CubemapLayoutType = 5
)

// TextureWrapMode as declared in ray/raylib.h:790
type TextureWrapMode int32

// TextureWrapMode enumeration from ray/raylib.h:790
const (
	WRAPREPEAT       TextureWrapMode = iota
	WRAPCLAMP        TextureWrapMode = 1
	WRAPMIRRORREPEAT TextureWrapMode = 2
	WRAPMIRRORCLAMP  TextureWrapMode = 3
)

// FontType as declared in ray/raylib.h:797
type FontType int32

// FontType enumeration from ray/raylib.h:797
const (
	FONTDEFAULT FontType = iota
	FONTBITMAP  FontType = 1
	FONTSDF     FontType = 2
)

// BlendMode as declared in ray/raylib.h:804
type BlendMode int32

// BlendMode enumeration from ray/raylib.h:804
const (
	BLENDALPHA      BlendMode = iota
	BLENDADDITIVE   BlendMode = 1
	BLENDMULTIPLIED BlendMode = 2
)

// GestureType as declared in ray/raylib.h:820
type GestureType int32

// GestureType enumeration from ray/raylib.h:820
const (
	GESTURENONE       GestureType = iota
	GESTURETAP        GestureType = 1
	GESTUREDOUBLETAP  GestureType = 2
	GESTUREHOLD       GestureType = 4
	GESTUREDRAG       GestureType = 8
	GESTURESWIPERIGHT GestureType = 16
	GESTURESWIPELEFT  GestureType = 32
	GESTURESWIPEUP    GestureType = 64
	GESTURESWIPEDOWN  GestureType = 128
	GESTUREPINCHIN    GestureType = 256
	GESTUREPINCHOUT   GestureType = 512
)

// CameraMode as declared in ray/raylib.h:829
type CameraMode int32

// CameraMode enumeration from ray/raylib.h:829
const (
	CAMERACUSTOM      CameraMode = iota
	CAMERAFREE        CameraMode = 1
	CAMERAORBITAL     CameraMode = 2
	CAMERAFIRSTPERSON CameraMode = 3
	CAMERATHIRDPERSON CameraMode = 4
)

// CameraType as declared in ray/raylib.h:835
type CameraType int32

// CameraType enumeration from ray/raylib.h:835
const (
	CAMERAPERSPECTIVE  CameraType = iota
	CAMERAORTHOGRAPHIC CameraType = 1
)

// NPatchType as declared in ray/raylib.h:842
type NPatchType int32

// NPatchType enumeration from ray/raylib.h:842
const (
	NPT9PATCH           NPatchType = iota
	NPT3PATCHVERTICAL   NPatchType = 1
	NPT3PATCHHORIZONTAL NPatchType = 2
)
